describe('Edit Data Akun User Oleh Admin', () => {
    // Data Login Admin
    const email = 'k.natanael88@gmail.com';
    const password = '123456';
    // Data Edit Form
    const nama = 'Andi Mushawwir Rahmat';
    const umur = '25';
    const berat = '65';
    const alamatRumah = 'Jalan Cakalang No.1';
    const kelurahan = 'Pandanwangi';
    const kota = 'Malang';
    const kecamatan = 'Blimbing';
    const nomorTelepon = '0823123211';
    it('Edit Data dengan Form Terisi Sempurna', () => {
        cy.visit('http://localhost:8000/')
        cy.get(':nth-child(8) > a').click()
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(email)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > :nth-child(4) > a').click()
        cy.get('[href="http://localhost:8000/admin/user/edit/2"]').click()
        cy.get(':nth-child(2) > #input-field > .form-control').clear()
        cy.get(':nth-child(2) > #input-field > .form-control').type(nama)
        cy.get(':nth-child(3) > #input-field > .form-control').clear()
        cy.get(':nth-child(3) > #input-field > .form-control').type(umur)
        cy.get('.input-group > .form-control').clear()
        cy.get('.input-group > .form-control').type(berat)
        cy.get(':nth-child(5) > #input-field > .form-control').clear()
        cy.get(':nth-child(5) > #input-field > .form-control').type(alamatRumah)
        cy.get(':nth-child(6) > #input-field > .form-control').clear()
        cy.get(':nth-child(6) > #input-field > .form-control').type(kelurahan)
        cy.get(':nth-child(7) > #input-field > .form-control').clear()
        cy.get(':nth-child(7) > #input-field > .form-control').type(kota)
        cy.get(':nth-child(8) > #input-field > .form-control').clear()
        cy.get(':nth-child(8) > #input-field > .form-control').type(kecamatan)
        cy.get(':nth-child(9) > #input-field > .form-control').clear()
        cy.get(':nth-child(9) > #input-field > .form-control').type(nomorTelepon)
        cy.get('.btn').click()
    })

    it('Edit Data dengan Field Nama Kosong', () => {
        cy.visit('http://localhost:8000/')
        cy.get(':nth-child(8) > a').click()
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(email)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > :nth-child(4) > a').click()
        cy.get('[href="http://localhost:8000/admin/user/edit/2"]').click()
        cy.get(':nth-child(2) > #input-field > .form-control').clear()
        cy.get(':nth-child(3) > #input-field > .form-control').clear()
        cy.get(':nth-child(3) > #input-field > .form-control').type(umur)
        cy.get('.input-group > .form-control').clear()
        cy.get('.input-group > .form-control').type(berat)
        cy.get(':nth-child(5) > #input-field > .form-control').clear()
        cy.get(':nth-child(5) > #input-field > .form-control').type(alamatRumah)
        cy.get(':nth-child(6) > #input-field > .form-control').clear()
        cy.get(':nth-child(6) > #input-field > .form-control').type(kelurahan)
        cy.get(':nth-child(7) > #input-field > .form-control').clear()
        cy.get(':nth-child(7) > #input-field > .form-control').type(kota)
        cy.get(':nth-child(8) > #input-field > .form-control').clear()
        cy.get(':nth-child(8) > #input-field > .form-control').type(kecamatan)
        cy.get(':nth-child(9) > #input-field > .form-control').clear()
        cy.get(':nth-child(9) > #input-field > .form-control').type(nomorTelepon)
        cy.get('.btn').click()
    })

    it('Edit Data dengan Field Umur Kosong', () => {
        cy.visit('http://localhost:8000/')
        cy.get(':nth-child(8) > a').click()
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(email)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > :nth-child(4) > a').click()
        cy.get('[href="http://localhost:8000/admin/user/edit/2"]').click()
        cy.get(':nth-child(2) > #input-field > .form-control').clear()
        cy.get(':nth-child(2) > #input-field > .form-control').type(nama)
        cy.get(':nth-child(3) > #input-field > .form-control').clear()
        cy.get('.input-group > .form-control').clear()
        cy.get('.input-group > .form-control').type(berat)
        cy.get(':nth-child(5) > #input-field > .form-control').clear()
        cy.get(':nth-child(5) > #input-field > .form-control').type(alamatRumah)
        cy.get(':nth-child(6) > #input-field > .form-control').clear()
        cy.get(':nth-child(6) > #input-field > .form-control').type(kelurahan)
        cy.get(':nth-child(7) > #input-field > .form-control').clear()
        cy.get(':nth-child(7) > #input-field > .form-control').type(kota)
        cy.get(':nth-child(8) > #input-field > .form-control').clear()
        cy.get(':nth-child(8) > #input-field > .form-control').type(kecamatan)
        cy.get(':nth-child(9) > #input-field > .form-control').clear()
        cy.get(':nth-child(9) > #input-field > .form-control').type(nomorTelepon)
        cy.get('.btn').click()
    })

    it('Edit Data dengan Field Berat Kosong', () => {
        cy.visit('http://localhost:8000/')
        cy.get(':nth-child(8) > a').click()
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(email)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > :nth-child(4) > a').click()
        cy.get('[href="http://localhost:8000/admin/user/edit/2"]').click()
        cy.get(':nth-child(2) > #input-field > .form-control').clear()
        cy.get(':nth-child(2) > #input-field > .form-control').type(nama)
        cy.get(':nth-child(3) > #input-field > .form-control').clear()
        cy.get(':nth-child(3) > #input-field > .form-control').type(umur)
        cy.get('.input-group > .form-control').clear()
        cy.get(':nth-child(5) > #input-field > .form-control').clear()
        cy.get(':nth-child(5) > #input-field > .form-control').type(alamatRumah)
        cy.get(':nth-child(6) > #input-field > .form-control').clear()
        cy.get(':nth-child(6) > #input-field > .form-control').type(kelurahan)
        cy.get(':nth-child(7) > #input-field > .form-control').clear()
        cy.get(':nth-child(7) > #input-field > .form-control').type(kota)
        cy.get(':nth-child(8) > #input-field > .form-control').clear()
        cy.get(':nth-child(8) > #input-field > .form-control').type(kecamatan)
        cy.get(':nth-child(9) > #input-field > .form-control').clear()
        cy.get(':nth-child(9) > #input-field > .form-control').type(nomorTelepon)
        cy.get('.btn').click()
    })

    it('Edit Data dengan Field Alamat Rumah Kosong', () => {
        cy.visit('http://localhost:8000/')
        cy.get(':nth-child(8) > a').click()
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(email)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > :nth-child(4) > a').click()
        cy.get('[href="http://localhost:8000/admin/user/edit/2"]').click()
        cy.get(':nth-child(2) > #input-field > .form-control').clear()
        cy.get(':nth-child(2) > #input-field > .form-control').type(nama)
        cy.get(':nth-child(3) > #input-field > .form-control').clear()
        cy.get(':nth-child(3) > #input-field > .form-control').type(umur)
        cy.get('.input-group > .form-control').clear()
        cy.get('.input-group > .form-control').type(berat)
        cy.get(':nth-child(5) > #input-field > .form-control').clear()
        cy.get(':nth-child(6) > #input-field > .form-control').clear()
        cy.get(':nth-child(6) > #input-field > .form-control').type(kelurahan)
        cy.get(':nth-child(7) > #input-field > .form-control').clear()
        cy.get(':nth-child(7) > #input-field > .form-control').type(kota)
        cy.get(':nth-child(8) > #input-field > .form-control').clear()
        cy.get(':nth-child(8) > #input-field > .form-control').type(kecamatan)
        cy.get(':nth-child(9) > #input-field > .form-control').clear()
        cy.get(':nth-child(9) > #input-field > .form-control').type(nomorTelepon)
        cy.get('.btn').click()
    })

    it('Edit Data dengan Field Kelurahan Kosong', () => {
        cy.visit('http://localhost:8000/')
        cy.get(':nth-child(8) > a').click()
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(email)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > :nth-child(4) > a').click()
        cy.get('[href="http://localhost:8000/admin/user/edit/2"]').click()
        cy.get(':nth-child(2) > #input-field > .form-control').clear()
        cy.get(':nth-child(2) > #input-field > .form-control').type(nama)
        cy.get(':nth-child(3) > #input-field > .form-control').clear()
        cy.get(':nth-child(3) > #input-field > .form-control').type(umur)
        cy.get('.input-group > .form-control').clear()
        cy.get('.input-group > .form-control').type(berat)
        cy.get(':nth-child(5) > #input-field > .form-control').clear()
        cy.get(':nth-child(5) > #input-field > .form-control').type(alamatRumah)
        cy.get(':nth-child(6) > #input-field > .form-control').clear()
        cy.get(':nth-child(6) > #input-field > .form-control').type(kelurahan)
        cy.get(':nth-child(7) > #input-field > .form-control').clear()
        cy.get(':nth-child(7) > #input-field > .form-control').type(kota)
        cy.get(':nth-child(8) > #input-field > .form-control').clear()
        cy.get(':nth-child(9) > #input-field > .form-control').clear()
        cy.get(':nth-child(9) > #input-field > .form-control').type(nomorTelepon)
        cy.get('.btn').click()
    })

    it('Edit Data dengan Field Kecamatan Kosong', () => {
        cy.visit('http://localhost:8000/')
        cy.get(':nth-child(8) > a').click()
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(email)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > :nth-child(4) > a').click()
        cy.get('[href="http://localhost:8000/admin/user/edit/2"]').click()
        cy.get(':nth-child(2) > #input-field > .form-control').clear()
        cy.get(':nth-child(2) > #input-field > .form-control').type(nama)
        cy.get(':nth-child(3) > #input-field > .form-control').clear()
        cy.get(':nth-child(3) > #input-field > .form-control').type(umur)
        cy.get('.input-group > .form-control').clear()
        cy.get('.input-group > .form-control').type(berat)
        cy.get(':nth-child(5) > #input-field > .form-control').clear()
        cy.get(':nth-child(5) > #input-field > .form-control').type(alamatRumah)
        cy.get(':nth-child(6) > #input-field > .form-control').clear()
        cy.get(':nth-child(7) > #input-field > .form-control').clear()
        cy.get(':nth-child(7) > #input-field > .form-control').type(kota)
        cy.get(':nth-child(8) > #input-field > .form-control').clear()
        cy.get(':nth-child(8) > #input-field > .form-control').type(kecamatan)
        cy.get(':nth-child(9) > #input-field > .form-control').clear()
        cy.get(':nth-child(9) > #input-field > .form-control').type(nomorTelepon)
        cy.get('.btn').click()
    })

    it('Edit Data dengan Field Kota Kosong', () => {
        cy.visit('http://localhost:8000/')
        cy.get(':nth-child(8) > a').click()
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(email)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > :nth-child(4) > a').click()
        cy.get('[href="http://localhost:8000/admin/user/edit/2"]').click()
        cy.get(':nth-child(2) > #input-field > .form-control').clear()
        cy.get(':nth-child(2) > #input-field > .form-control').type(nama)
        cy.get(':nth-child(3) > #input-field > .form-control').clear()
        cy.get(':nth-child(3) > #input-field > .form-control').type(umur)
        cy.get('.input-group > .form-control').clear()
        cy.get('.input-group > .form-control').type(berat)
        cy.get(':nth-child(5) > #input-field > .form-control').clear()
        cy.get(':nth-child(5) > #input-field > .form-control').type(alamatRumah)
        cy.get(':nth-child(6) > #input-field > .form-control').clear()
        cy.get(':nth-child(6) > #input-field > .form-control').type(kelurahan)
        cy.get(':nth-child(7) > #input-field > .form-control').clear()
        cy.get(':nth-child(8) > #input-field > .form-control').clear()
        cy.get(':nth-child(8) > #input-field > .form-control').type(kecamatan)
        cy.get(':nth-child(9) > #input-field > .form-control').clear()
        cy.get(':nth-child(9) > #input-field > .form-control').type(nomorTelepon)
        cy.get('.btn').click()
    })

    it('Edit Data dengan Field Nomor Telepon Kosong', () => {
        cy.visit('http://localhost:8000/')
        cy.get(':nth-child(8) > a').click()
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(email)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > :nth-child(4) > a').click()
        cy.get('[href="http://localhost:8000/admin/user/edit/2"]').click()
        cy.get(':nth-child(2) > #input-field > .form-control').clear()
        cy.get(':nth-child(2) > #input-field > .form-control').type(nama)
        cy.get(':nth-child(3) > #input-field > .form-control').clear()
        cy.get(':nth-child(3) > #input-field > .form-control').type(umur)
        cy.get('.input-group > .form-control').clear()
        cy.get('.input-group > .form-control').type(berat)
        cy.get(':nth-child(5) > #input-field > .form-control').clear()
        cy.get(':nth-child(5) > #input-field > .form-control').type(alamatRumah)
        cy.get(':nth-child(6) > #input-field > .form-control').clear()
        cy.get(':nth-child(6) > #input-field > .form-control').type(kelurahan)
        cy.get(':nth-child(7) > #input-field > .form-control').clear()
        cy.get(':nth-child(7) > #input-field > .form-control').type(kota)
        cy.get(':nth-child(8) > #input-field > .form-control').clear()
        cy.get(':nth-child(8) > #input-field > .form-control').type(kecamatan)
        cy.get(':nth-child(9) > #input-field > .form-control').clear()
        cy.get('.btn').click()
    })

    it('Edit Data dengan Semua Field Kosong', () => {
        cy.visit('http://localhost:8000/')
        cy.get(':nth-child(8) > a').click()
        cy.get(':nth-child(2) > .col-md-6 > .form-control').type(email)
        cy.get(':nth-child(3) > .col-md-6 > .form-control').type(password)
        cy.get('.btn-primary').click()
        cy.get('.dropdown-toggle').click()
        cy.get('.dropdown-menu > :nth-child(4) > a').click()
        cy.get('[href="http://localhost:8000/admin/user/edit/2"]').click()
        cy.get(':nth-child(2) > #input-field > .form-control').clear()
        cy.get(':nth-child(3) > #input-field > .form-control').clear()
        cy.get('.input-group > .form-control').clear()
        cy.get(':nth-child(5) > #input-field > .form-control').clear()
        cy.get(':nth-child(6) > #input-field > .form-control').clear()
        cy.get(':nth-child(7) > #input-field > .form-control').clear()
        cy.get(':nth-child(8) > #input-field > .form-control').clear()
        cy.get(':nth-child(9) > #input-field > .form-control').clear()
        cy.get('.btn').click()
    })
})